### ISSUE TITLE
Tag a Version, Pip Upload

### ISSUE THREAD

**Issue by ax3l** [hightower8083/axiprop#8]
We currently prepare to upload `lasy` to pypi, since we need it for CI workflows in WarpX.
https://github.com/LASY-org/lasy/pull/131
cc @RemiLehe

The upload to pypi fails because we cannot depend on axiprop in `requirements.txt` as we currently do:
```
axiprop @ https://github.com/hightower8083/axiprop/archive/refs/heads/main.zip
# or
axiprop @ git+https://github.com/hightower8083/axiprop.git@9bd516898c1cc4e1bcbfb9adac26f8909ec087a0
```

@hightower8083 can you please prepare a PR similar to https://github.com/LASY-org/lasy/pull/131, tag a version of axiprop, and upload it to PyPI?

Thanks for your help! :)

**Comment by hightower8083** [comment]
it's done 
https://pypi.org/project/axiprop/0.5/

**Comment by ax3l** [comment]
Awesome, thanks a lot :rocket: :sparkles:
